### ISSUE TITLE
Offset out of range error?

### ISSUE THREAD

**Issue by Cptnkoala** [UserMcUser/node-MVM#2]
after a few years, I came back to this project and found the newest version working with the latest copy of artemis. Set everything back up, and tested it and it worked great, but after about a minute, I receive this error.

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 193. Received 2181038210
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readUInt8 (internal/buffer.js:243:5)
    at Socket.<anonymous> (C:\Users\Mary\Desktop\New folder\node-MVM-master\node-MVM-master\mvm.js:214:35)
    at Socket.emit (events.js:316:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by UserMcUser** [comment]
Does it crash like that every time?

Try un-commenting lines 212 and 213 in your local copy and then paste the console results here.

**Comment by Cptnkoala** [comment]
Yes it crashes like that every time.
After uncommenting those lines, the output is as follows.

C:\Users\Mary\Desktop\games\Artemis\node-MVM-master\node-MVM-master>node mvm -l 3010 -f 2010 -v 3 -s 127.0.0.1
(node:1700) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Mainscreen View Manager v1.3.0

Listening on port 3010
Relaying to 127.0.0.1 port 2010

View will be set to: Aft

Use Control+C to quit.
bitmap:  <Buffer 80 a8 01 08 00>
Buffer Index:  55
Server Says the mainScreen view is:  Port
But we are sending:  Aft
bitmap:  <Buffer ff ff ff ff ff>
Buffer Index:  2181038210
internal/buffer.js:77
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 193. Received 2181038210
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readUInt8 (internal/buffer.js:243:5)
    at Socket.<anonymous> (C:\Users\Mary\Desktop\games\Artemis\node-MVM-master\node-MVM-master\mvm.js:214:35)
    at Socket.emit (events.js:316:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by UserMcUser** [comment]
OK thanks - that is very helpful. Looks like I'm getting some default value back from my unpackBitmap function.

I should have some time this weekend to look into this further.

**Comment by UserMcUser** [comment]
My apologies - have not had time to look at this with an actual Artemis client yet. Will advise further.

**Comment by UserMcUser** [comment]
If you can, please try the patched version here: https://github.com/UserMcUser/node-MVM/tree/UserMcUser-patch-1

I added a quick-and-dirty check of the offending value so that the program doesn't crash. However, I think the underlying protocol may have changed. So MVM may not crash but it also may not work.

If you can test this and let me know I would appreciate it. As soon as I am able I will do some real work on this.

**Comment by NoseyNick** [comment]
See https://artemis.forumchitchat.com/post/mvm-mainscreen-view-manager-7470121?highlight=mvm&trail=60

I THINK Artemis 2.7.X and 2.8.0 require your `fieldBytes ... 4,4,2,0` to be `... 4,4,1,0`
Not sure if you want to extend the `oldVersion` to include 3 version-ranges?

... or might be time to ditch support for reeeeeeally old versions, and make it so oldVersion just changes that 18th field length from 2 to 1 for "2.3.X to 2.6.X" vs "2.7.X and 2.8.X" and forget about 2.2.X and below?

See https://artemis-nerds.github.io/protocol-docs/#object-player-ship for details

NN

**Comment by NoseyNick** [comment]
See #3 ... or my fork at https://github.com/NoseyNick/node-MVM

I have obsoleted `--oldVersion` (made it auto-detect Artemis protocol version instead) and added support up to Artemis 2.8.0, probably 2.8.1.

:warning: **NOT WELL TESTED** - appreciate some help there   :grinning: :rocket:
